from unification import Unification
from histogram_gray import HistogramGray
from histogram_color import HistogramColor
from arithmetic_color import ArithmeticColor
from arithmetic_gray import ArithmeticGray
from geometric import Geometric
from morpho_bin import MorphoBin
from morpho_gray import MorphoGray


from filter import Filter

zad1 = "img/zad1/"
zad5 = "img/zad5/"
zad6 = "img/zad6/"
zad9 = "img/zad9/"

ex1 = Unification(zad1 + "pirate_gray.tiff", zad1 + "gentelman_gray.tiff")
ex1.geometricGray(show=True)
ex1.rasterGray(show=True)
ex1.load(zad1 + "peppers_color.tiff", zad1 + "lena_color.tiff")
ex1.geometricColor(show=True)
ex1.rasterColor(show=True)
# ex1.load(zad1 + "boat_gray.tiff", zad1 + "clock_gray.tiff")
# ex1.geometricGray(show=True)
# ex1.rasterGray(show=True)
# ex1.load(zad1 + "mandrill_color.tiff", zad1 + "candy_color.tiff")
# ex1.geometricColor(show=True)
# ex1.rasterColor(show=True)
# ##
##


ex2a = ArithmeticGray(image1Path = "../../Resources/Gray/Zegarek.tiff", image2Path = "../../Resources/Gray/Gentelman.tiff")
ex2a.sum_const(const = 50, show = True, save = True)
ex2a.sum_img(show = True, save = True)
ex2a.multiply_const(const = 50, show = True, save = True)
ex2a.multiply_img(show = True, save = True)
ex2a.mix_alfa(alfa = 0.5, show = True, save = True)
ex2a.pow_img(alfa = 2, show = True, save = True)
ex2a.sqrt_img(deg = 2, show = True, save = True)
ex2a.log_img(True, save = True)
ex2a.div_const(15, True, True)
ex2a.div_img(True, True)

ex2b = ArithmeticGray(im1Name_ = "2", image1Path = "../../Resources/Gray/Pirat.tiff", image2Path = "../../Resources/Gray/Statek.tiff")
ex2b.sum_const(const = 100, show = True, save = True)
ex2b.sum_img(show = True, save = True)
ex2b.multiply_const(const = 100, show = True, save = True)
ex2b.multiply_img(show = True, save = True)
ex2b.mix_alfa(alfa = 0.8, show = True, save = True)
ex2b.pow_img(alfa = 3, show = True, save = True)
ex2b.sqrt_img(deg = 3, show = True, save = True)
ex2b.log_img(True, save = True)
ex2b.div_const(3, True, save = True)
ex2b.div_img(True, True)

ex3a = ArithmeticColor(im1Name_="1", image1Path = "../../Resources/Color/Warzywa.tiff", image2Path = "../../Resources/Color/Statek.tiff" )
ex3a.sum_const(const = 50, show = True, save = True)
ex3a.sum_img(show = True, save = True)
ex3a.multiply_const(const = 50, show = True, save = True)
ex3a.multiply_img(show = True, save = True)
ex3a.mix_alfa(alfa = 0.5, show = True, save = True)
ex3a.pow_img(alfa = 2, show = True, save = True)
ex3a.sqrt_img(deg = 2, show = True, save = True)
ex3a.log_img(True, True)
ex3a.div_const(15, True, True)
ex3a.div_img(True, True)

ex3b = ArithmeticColor(im1Name_="2", image1Path = "../../Resources/Color/Cukierki.tiff", image2Path = "../../Resources/Color/Kobieta.tiff" )
ex3b.sum_const(const = 100, show = True, save = True)
ex3b.sum_img(show = True, save = True)
ex3b.multiply_const(const = 100, show = True, save = True)
ex3b.multiply_img(show = True, save = True)
ex3b.mix_alfa(alfa = 0.8, show = True, save = True)
ex3b.pow_img(alfa = 3, show = True, save = True)
ex3b.sqrt_img(deg = 3, show = True, save = True)
ex3b.log_img(True, True)
ex3b.div_const(3, True, True)
ex3b.div_img(True, True)

ex4a = Geometric(image1Path = "../../Resources/Color/Warzywa.tiff", image2Path = "../../Resources/Color/Szympans.tiff" )
ex4a.move(40, 70, True, True)
ex4a.scale_nj(2, 1, True, True)
ex4a.scale_j(1.5, True, True)
ex4a.turn(45, True, True)
ex4a.sym_x(True, True)
ex4a.sym_y(True, True)
ex4a.sym_paramx(show = True, save = True)
ex4a.sym_paramy(show = True, save = True)
ex4a.cut_frg(100,250,25,450, True, True)
ex4a.copy_frg(100,250,25,450, True, True)

ex4b = Geometric(im1Name_='2', image1Path = "../../Resources/Color/Statek.tiff", image2Path = "../../Resources/Color/Szympans.tiff" )
ex4b.move(200, 100, True, True)
ex4b.scale_nj(1, 2, True, True)
ex4b.scale_j(2, True, True)
ex4b.turn(110, True, True)
ex4b.sym_x(True, True)
ex4b.sym_y(True, True)
ex4b.sym_paramx(show = True, save = True)
ex4b.sym_paramy(show = True, save = True)
ex4b.cut_frg(200,400,200,400, True, True)
ex4b.copy_frg(200,400,200,400, True, True)


ex5 = HistogramGray(zad5 + "gentelman_gray.tiff")
ex5.calculate(plot=True, image=None)
ex5.move(const=100, show=True, plot=True)
ex5.stretch(show=True, plot=True)
ex5.localThreshold(dim=21, show=True, plot=True)
ex5.globalThreshold(show=True, plot=True)
ex5.load(zad5 + "pirate_gray.tiff")
ex5.calculate(plot=True, image=None)
ex5.move(const=-100, show=True, plot=True)
ex5.stretch(show=True, plot=True)
ex5.localThreshold(dim=21, show=True, plot=True)
ex5.globalThreshold(show=True, plot=True)
##
##
ex6 = HistogramColor(zad6 + "lena_color.tiff")
ex6.calculate(plot=True)
ex6.move(50, show=True, plot=True)
ex6.stretch(show=True, plot=True)
ex6.monoThresholding(show=True, plot=True)
ex6.globalSingleThreshold(show=True, plot=True)
ex6.globalMultiThreshold(bins=4, show=True, plot=True)
ex6.localSingleThreshold(dim=21, show=True, plot=True)
ex6.localMultiThreshold(dim=21, bins=4, show=True, plot=True)
ex6.load(zad6 + "peppers_color.tiff")
ex6.calculate(plot=True)
ex6.move(-50, show=True, plot=True)
ex6.stretch(show=True, plot=True)
ex6.monoThresholding(show=True, plot=True)
ex6.globalSingleThreshold(show=True, plot=True)
ex6.globalMultiThreshold(bins=4, show=True, plot=True)
ex6.localSingleThreshold(dim=21, show=True, plot=True)
ex6.localMultiThreshold(dim=21, bins=4, show=True, plot=True)
##

ex7a = MorphoBin(image1Path = "../../Resources/Binary/Circles.tiff")
ex7a.erozion(True, True)
ex7a.dilation(True, True)
ex7a.opening(True, True)
ex7a.closing(True, True)

ex7b = MorphoBin("2", image1Path = "../../Resources/Binary/Kwadrat.tiff")
ex7b.erozion(True, True)
ex7b.dilation(True, True)
ex7b.opening(True, True)
ex7b.closing(True, True)
##

ex8a = MorphoGray(image1Path = "../../Resources/Gray/Zegarek.tiff")
ex8a.erozion(True, True)
ex8a.dilation(True, True)
ex8a.opening(True, True)
ex8a.closing(True, True)

ex8b = MorphoGray("2", image1Path = "../../Resources/Gray/Statek.tiff")
ex8b.erozion(True, True)
ex8b.dilation(True, True)
ex8b.opening(True, True)
ex8b.closing(True, True)

##
ex9 = Filter(zad9 + "gentelman_gray.tiff")
ex9.averageGray(show=True)
ex9.gaussGray(show=True)
ex9.robertsGray(show=True)
ex9.prewittGray(show=True)
ex9.sobolGray(show=True)
ex9.compassGray(show=True)
ex9.reliefGray(show=True)
ex9.VDGGray(show=True)
ex9.medianGray(show=True)
ex9.maxGray(show=True)
ex9.minGray(show=True)
ex9.load(zad9 + "pirate_gray.tiff")
ex9.averageGray(show=True)
ex9.gaussGray(show=True)
ex9.robertsGray(show=True)
ex9.prewittGray(show=True)
ex9.sobolGray(show=True)
ex9.compassGray(show=True)
ex9.reliefGray(show=True)
ex9.VDGGray(show=True)
ex9.medianGray(show=True)
ex9.maxGray(show=True)
ex9.minGray(show=True)
ex9.load(zad9 + "lena_color.tiff")
ex9.averageColor(show=True)
ex9.gaussColor(show=True)
ex9.robertsColor(show=True)
ex9.prewittColor(show=True)
ex9.sobolColor(show=True)
ex9.compassColor(show=True)
ex9.reliefColor(show=True)
ex9.VDGColor(show=True)
ex9.medianColor(show=True)
ex9.maxColor(show=True)
ex9.minColor(show=True)
ex9.load(zad9 + "peppers_color.tiff")
ex9.averageColor(show=True)
ex9.gaussColor(show=True)
ex9.robertsColor(show=True)
ex9.prewittColor(show=True)
ex9.sobolColor(show=True)
ex9.compassColor(show=True)
ex9.reliefColor(show=True)
ex9.VDGColor(show=True)
ex9.medianColor(show=True)
ex9.maxColor(show=True)
ex9.minColor(show=True)
