from unification import Unification
from histogram_gray import HistogramGray
from histogram_color import HistogramColor
from filter import Filter
import  numpy as np
import math

zad1 = "img/zad1/"
zad5 = "img/zad5/"
zad6 = "img/zad6/"
zad9 = "img/zad9/"

#ex1 = Unification(zad1 + "airplane_gray.tiff", zad1 + "chemical_plant_gray.tiff")
#ex1.geometricGray(show=False)
#ex1.load(zad1 + "mandrill_color.tiff", zad1 + "jelly_beans_color.tiff")
#ex1.geometricColor(show=False)
#
#ex5 = HistogramGray(zad5 + "clock_gray.tiff")
##ex5.calculate(plot=True, image=None)
#ex5.move(const=-100, show=False, plot=False)
#ex5.stretch(show=False, plot=False)
#ex5.localThreshold(dim=20, show=False, plot=False)
#ex5.globalThreshold(show=False, plot=False)
#ex5.load(imagePath=zad5 + "gentelman_gray.tiff")
#ex5.move(const=-100, show=False, plot=False)
#ex5.stretch(show=False, plot=False)
#ex5.localThreshold(dim=20, show=False, plot=False)
#ex5.globalThreshold(show=False, plot=False)
#ex5.load(imagePath=zad5 + "pirate_gray.tiff")
#ex5.move(const=-100, show=False, plot=False)
#ex5.stretch(show=False, plot=False)
#ex5.localThreshold(dim=20, show=False, plot=False)
#ex5.globalThreshold(show=False, plot=False)
#ex5.load(imagePath=zad5 + "traffic_gray.tiff")
#ex5.move(const=-100, show=False, plot=False)
#ex5.stretch(show=False, plot=False)
#ex5.localThreshold(dim=20, show=False, plot=False)
#ex5.globalThreshold(show=False, plot=False)
#
#ex6 = HistogramColor(zad6 + "peppers_color.tiff")
##ex6.calculate(True)
#ex6.move(50, show=False, plot=False)
#ex6.stretch(show=False, plot=False)
#ex6.monoThresholding(show=False, plot=False)
#ex6.poliThresholding(bins=4, show=False, plot=False)
#ex6.localThreshold(dim=3, show=False, plot=False)
#ex6.globalThreshold(show=False, plot=False)
#ex6.load(zad6 + "female_color.tiff")
#ex6.move(50, show=False, plot=False)
#ex6.stretch(show=False, plot=False)
#ex6.monoThresholding(show=False, plot=False)
#ex6.poliThresholding(bins=4, show=False, plot=False)
#ex6.localThreshold(dim=3, show=False, plot=False)
#ex6.globalThreshold(show=False, plot=False)
#ex6.load(zad6 + "female1_color.tiff")
#ex6.move(50, show=False, plot=False)
#ex6.stretch(show=False, plot=False)
#ex6.monoThresholding(show=False, plot=False)
#ex6.poliThresholding(bins=4, show=False, plot=False)
#ex6.localThreshold(dim=3, show=False, plot=False)
#ex6.globalThreshold(show=False, plot=False)
#ex6.load(zad6 + "airplane_color.tiff")
#ex6.move(50, show=False, plot=False)
#ex6.stretch(show=False, plot=False)
#ex6.monoThresholding(show=False, plot=False)
#ex6.poliThresholding(bins=4, show=False, plot=False)
#ex6.localThreshold(dim=3, show=False, plot=False)
#ex6.globalThreshold(show=False, plot=False)
#
ex9 = Filter(zad9 + "female_color.tiff")
#ex9.averageColor(show=False)
#ex9.gaussColor(show=False)
#ex9.robertsColor(show=False)
#ex9.prewittColor(show=False)
#ex9.sobolColor(show=False)
#ex9.compassColor(show=False)
#ex9.reliefColor(show=False)
#ex9.medianColor(show=False)
#ex9.maxColor(show=False)
#ex9.minColor(show=False)
#ex9.load(zad9 + "gentelman_gray.tiff")
#ex9.averageGray(show=False)
#ex9.gaussGray(show=False)
#ex9.robertsGray(show=False)
#ex9.prewittGray(show=False)
#ex9.sobolGray(show=False)
#ex9.compassGray(show=False)
#ex9.reliefGray(show=False)
#ex9.medianGray(show=False)
#ex9.maxGray(show=False)
#ex9.minGray(show=False)
#ex9.load(zad9 + "pirate_gray.tiff")
#ex9.averageGray(show=False)
#ex9.gaussGray(show=False)
#ex9.robertsGray(show=False)
#ex9.prewittGray(show=False)
#ex9.sobolGray(show=False)
#ex9.compassGray(show=False)
#ex9.reliefGray(show=False)
#ex9.medianGray(show=False)
#ex9.maxGray(show=False)
#ex9.minGray(show=False)
ex9.load(zad9 + "hause_color.tiff")
ex9.averageColor(show=False)
ex9.gaussColor(show=False)
ex9.robertsColor(show=False)
ex9.prewittColor(show=False)
ex9.sobolColor(show=False)
ex9.compassColor(show=False)
ex9.reliefColor(show=False)
ex9.medianColor(show=False)
ex9.maxColor(show=False)
ex9.minColor(show=False)
